In [1]:
import math


In [2]:
math.pi


3.141592653589793

In [3]:
math.e


2.718281828459045

In [4]:
math.inf


inf

In [5]:
math.ceil(7.8)


8

In [6]:
math.floor(7.99)


7

In [7]:
float_list = [0.1] * 10
float_list


[0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1]

In [8]:
sum(float_list)


0.9999999999999999

In [9]:
math.fsum(float_list)


1.0

In [10]:
# greatest common denominator
math.gcd(30,20)


10

In [11]:
math.gcd(3343, 223)


1

# installing and importing third party libraries


In [13]:
!pip install numpy


In [16]:
import numpy as np
some_list = list(range(1,8))


In [17]:
type(some_list)


list

In [18]:
some_list


[1, 2, 3, 4, 5, 6, 7]

In [19]:
some_array = np.array(some_list)
type(some_array)


numpy.ndarray

In [20]:
some_array


array([1, 2, 3, 4, 5, 6, 7])

In [21]:
ones_array = np.ones(5)
ones_array


array([1., 1., 1., 1., 1.])

In [22]:
range_array = np.arange(8)


In [24]:
print(range_array)


[0 1 2 3 4 5 6 7]


In [25]:
reshaped_array = range_array.reshape(2,4)
reshaped_array


array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [26]:
print(reshaped_array)


[[0 1 2 3]
 [4 5 6 7]]


In [28]:
reshaped_array = range_array.reshape(4,2)
reshaped_array


array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [30]:
random_array = np.random.random((4,5))
random_array


array([[0.25246514, 0.90523562, 0.71070471, 0.08116966, 0.37867904],
       [0.77598848, 0.45364275, 0.19715572, 0.17232416, 0.84814053],
       [0.77862171, 0.77496934, 0.68936837, 0.48973284, 0.74505506],
       [0.7425211 , 0.56972143, 0.7827491 , 0.90518023, 0.71523751]])

In [31]:
range_array


array([0, 1, 2, 3, 4, 5, 6, 7])

In [33]:
mean = np.mean(range_array)
mean

3.5

In [36]:
median = np.median(range_array)
median

3.5

In [38]:
variance = np.var(range_array)
variance


5.25

In [39]:
std = np.std(range_array)
std


2.29128784747792

In [40]:
!pip install pandas


In [41]:
import pandas as pd


In [45]:
df = pd.DataFrame(
    {
        'name': ['John', 'Alice', 'Bob', 'Eileen', 'Rob'],
        'gender': ["Male", "Female", "Male", "Female", "Male"],
        'age': [45, 20, 30, 14, 67],
    }
)
df


name  gender  age
0    John    Male   45
1   Alice  Female   20
2     Bob    Male   30
3  Eileen  Female   14
4     Rob    Male   67

In [46]:
df.describe()


age
count   5.000000
mean   35.200000
std    21.300235
min    14.000000
25%    20.000000
50%    30.000000
75%    45.000000
max    67.000000

In [48]:
subset_df = df[['name', 'age']]
subset_df

name  age
0    John   45
1   Alice   20
2     Bob   30
3  Eileen   14
4     Rob   67

In [49]:
groupby_df = df.groupby('gender').count()
groupby_df


name  age
gender           
Female     2    2
Male       3    3

In [50]:
groupby_df.describe()


name       age
count  2.000000  2.000000
mean   2.500000  2.500000
std    0.707107  0.707107
min    2.000000  2.000000
25%    2.250000  2.250000
50%    2.500000  2.500000
75%    2.750000  2.750000
max    3.000000  3.000000